// Généré par tauri-specta (cargo test -p crate-app). Ne pas modifier à la main.
// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	library: () => __TAURI_INVOKE<Library_Serialize>("library"),
	sources: () => __TAURI_INVOKE<Source[]>("sources"),
	tree: (req: TreeRequest) => __TAURI_INVOKE<TreePage_Serialize>("tree", { req }),
	setFavorite: (ids: number[], fav: boolean) => __TAURI_INVOKE<void>("set_favorite", { ids, fav }),
	addTag: (ids: number[], tag: string) => __TAURI_INVOKE<void>("add_tag", { ids, tag }),
	removeTag: (ids: number[], tag: string) => __TAURI_INVOKE<void>("remove_tag", { ids, tag }),
	createCollection: (name: string, query: string | null) => __TAURI_INVOKE<Collection_Serialize>("create_collection", { name, query }),
	renameCollection: (id: number, name: string) => __TAURI_INVOKE<void>("rename_collection", { id, name }),
	deleteCollection: (id: number) => __TAURI_INVOKE<void>("delete_collection", { id }),
	addToCollection: (id: number, ids: number[]) => __TAURI_INVOKE<void>("add_to_collection", { id, ids }),
	removeFromCollection: (id: number, ids: number[]) => __TAURI_INVOKE<void>("remove_from_collection", { id, ids }),
	createVirtualFolder: (name: string, parentId: number | null) => __TAURI_INVOKE<VirtualFolder>("create_virtual_folder", { name, parentId }),
	renameVirtualFolder: (id: number, name: string) => __TAURI_INVOKE<void>("rename_virtual_folder", { id, name }),
	deleteVirtualFolder: (id: number) => __TAURI_INVOKE<void>("delete_virtual_folder", { id }),
	moveVirtualFolder: (id: number, parentId: number | null) => __TAURI_INVOKE<void>("move_virtual_folder", { id, parentId }),
	addToVirtualFolder: (id: number, ids: number[]) => __TAURI_INVOKE<void>("add_to_virtual_folder", { id, ids }),
	removeFromVirtualFolder: (id: number, ids: number[]) => __TAURI_INVOKE<void>("remove_from_virtual_folder", { id, ids }),
	setPinned: (key: string, pinned: boolean) => __TAURI_INVOKE<void>("set_pinned", { key, pinned }),
	planCommit: (key: string, options: CommitOptions) => __TAURI_INVOKE<CommitPlan>("plan_commit", { key, options }),
	/**  Phase 1 : copie simulée (aucun fichier écrit). Phase 5 : copie réelle, avec progression par événement. */
	commitToFolder: (key: string, destination: string, options: CommitOptions) => __TAURI_INVOKE<CommitResult>("commit_to_folder", { key, destination, options }),
	removeSource: (id: number) => __TAURI_INVOKE<void>("remove_source", { id }),
	/**  Phase 5 : ouverture réelle dans le Finder. */
	revealInFinder: (path: string) => __TAURI_INVOKE<void>("reveal_in_finder", { path }),
	/**  Démo uniquement (scénario « Erreurs ») : marque des fichiers comme introuvables. */
	demoSetMissing: (ids: number[]) => __TAURI_INVOKE<void>("demo_set_missing", { ids }),
};

/* Types */
/**  Collection : simple regroupement de samples, à plat. Smart = recherche enregistrée. */
export type Collection = Collection_Serialize | Collection_Deserialize;

export type CollectionKind = "manual" | "smart";

/**  Collection : simple regroupement de samples, à plat. Smart = recherche enregistrée. */
export type Collection_Deserialize = {
	id: number,
	name: string,
	kind: CollectionKind,
	/**  Aussi affichée à la racine de l'onglet Bibliothèque. */
	pinned: boolean,
	/**  Ligne de recherche brute d'une collection smart. */
	query?: string | null,
};

/**  Collection : simple regroupement de samples, à plat. Smart = recherche enregistrée. */
export type Collection_Serialize = {
	id: number,
	name: string,
	kind: CollectionKind,
	/**  Aussi affichée à la racine de l'onglet Bibliothèque. */
	pinned: boolean,
	/**  Ligne de recherche brute d'une collection smart. */
	query?: string | null,
};

export type CommitOptions = {
	keepHierarchy: boolean,
	addAsSource: boolean,
};

/**  Ce que « Créer un vrai dossier » copierait. */
export type CommitPlan = {
	files: number,
	/**  Sous-dossiers créés (0 si l'arborescence est aplatie). */
	folders: number,
	/**
	 *  En octets (f64 : un u64 n'a pas d'équivalent sûr en JavaScript). Toujours fini : déclaré `number`
	 *  côté TypeScript (specta y verrait `number | null`).
	 */
	bytes: number,
	/**  Fichiers introuvables, ignorés. */
	missing: number,
};

export type CommitResult = {
	destination: string,
	copied: number,
	skipped: number,
};

export type FolderRow = FolderRow_Serialize | FolderRow_Deserialize;

export type FolderRow_Deserialize = {
	type: NodeTag,
	key: string,
	parent: string | null,
	depth: number,
	name: string,
	kind: NodeKind,
	open: boolean,
	offline?: boolean | null,
	/**  Collection ou dossier virtuel épinglé (repère dans l'onglet Bibliothèque). */
	pinned?: boolean | null,
};

export type FolderRow_Serialize = {
	type: NodeTag,
	key: string,
	parent: string | null,
	depth: number,
	name: string,
	kind: NodeKind,
	open: boolean,
	offline?: boolean | null,
	/**  Collection ou dossier virtuel épinglé (repère dans l'onglet Bibliothèque). */
	pinned?: boolean | null,
};

export type Library = Library_Serialize | Library_Deserialize;

export type Library_Deserialize = {
	total: number,
	tags: Tag[],
	collections: Collection_Deserialize[],
	virtualFolders: VirtualFolder[],
	favoritesPinned: boolean,
};

export type Library_Serialize = {
	total: number,
	tags: Tag[],
	collections: Collection_Serialize[],
	virtualFolders: VirtualFolder[],
	favoritesPinned: boolean,
};

export type NodeKind = "folder" | "favorites" | "group" | "collection" | "smart" | "virtual";

/**  Discriminant littéral `"node"` d'une ligne de dossier. */
export type NodeTag = "node";

export type Sample = {
	id: number,
	/**  Sans extension. */
	name: string,
	ext: string,
	path: string,
	folderId: number,
	durationMs: number,
	sampleRate: number,
	bitDepth: number,
	channels: number,
	bpm: number | null,
	key: string | null,
	kind: SampleKind,
	tags: string[],
	missing: boolean,
	fav: boolean,
	/**
	 *  256 valeurs 0..1, toujours finies. Déclaré `number[]` côté TypeScript (specta y verrait `number | null`,
	 *  à cause de NaN, qui n'arrive jamais ici).
	 */
	peaks: number[],
};

export type SampleKind = "oneshot" | "loop";

export type SampleRow = {
	type: SampleTag,
	/**  "s:<id>@<parent>" : un sample peut apparaître dans un dossier et une collection. */
	key: string,
	parent: string,
	depth: number,
	sample: Sample,
};

/**  Discriminant littéral `"sample"` d'une ligne de sample. */
export type SampleTag = "sample";

export type Source = {
	id: number,
	name: string,
	path: string,
	offline: boolean,
};

export type Tag = {
	name: string,
	count: number,
};

export type TreePage = TreePage_Serialize | TreePage_Deserialize;

export type TreePage_Deserialize = {
	rows: TreeRow_Deserialize[],
	totalRows: number,
	matches: number,
};

export type TreePage_Serialize = {
	rows: TreeRow_Serialize[],
	totalRows: number,
	matches: number,
};

export type TreeRequest = {
	root: TreeRoot,
	/**  Ligne de recherche brute. Non vide : arbre élagué aux nœuds qui contiennent des résultats, tous ouverts. */
	query: string,
	expanded: string[],
	offset: number,
	limit: number,
};

/**  Onglet : sources (+ éléments épinglés) ou favoris / collections / dossiers virtuels. */
export type TreeRoot = "library" | "virtual";

/**
 *  Une ligne de l'arbre, discriminée par le champ `type` ("node" ou "sample") porté par chaque struct.
 *  (`#[serde(untagged)]` + discriminant littéral : specta décrit mal `#[serde(tag)]` sur des variantes newtype.)
 */
export type TreeRow = TreeRow_Serialize | TreeRow_Deserialize;

/**
 *  Une ligne de l'arbre, discriminée par le champ `type` ("node" ou "sample") porté par chaque struct.
 *  (`#[serde(untagged)]` + discriminant littéral : specta décrit mal `#[serde(tag)]` sur des variantes newtype.)
 */
export type TreeRow_Deserialize = FolderRow_Deserialize | SampleRow;

/**
 *  Une ligne de l'arbre, discriminée par le champ `type` ("node" ou "sample") porté par chaque struct.
 *  (`#[serde(untagged)]` + discriminant littéral : specta décrit mal `#[serde(tag)]` sur des variantes newtype.)
 */
export type TreeRow_Serialize = FolderRow_Serialize | SampleRow;

/**  Dossier virtuel : arborescence de samples sans déplacer les fichiers. */
export type VirtualFolder = {
	id: number,
	name: string,
	/**  `None` = racine de l'onglet Virtuels. */
	parentId: number | null,
	pinned: boolean,
};

